name: Label Sync

on:
  push:
    branches:
      - main
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

permissions: read-all

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sync labels
        uses: EndBug/add-and-update-labels@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
